-- Publishes the remaining 80 reviewed Explained entries as editorial references.
-- Both image columns are populated because the database sync trigger treats image_uri as authoritative.
-- The source prefix keeps these third-party editorial references out of Screensaver.
-- This script does not grant or modify database permissions.

begin;

insert into public.memes
  (id, title, image_url, image_uri, kind, tags, source, meaning, origin, example, created_at)
values
  ('explained-18', 'Boardroom Suggestion', 'https://explained.meme/assets/explained-18-boardroom-suggestion.jpg', 'https://explained.meme/assets/explained-18-boardroom-suggestion.jpg', 'meme', array['explained','editorial-reference','workplace','corporate logic','rejection','webcomic'], 'explained_editorial_reference:https://knowyourmeme.com/memes/boardroom-suggestion', 'Shows a sensible proposal being punished while safer or worse ideas receive approval, usually mocking corporate decision-making.', 'Hejibits webcomic (2012)', 'More meetings. More dashboards. Fix the actual problem — thrown out of the window.', now()),
  ('explained-19', 'Gru''s Plan', 'https://explained.meme/assets/explained-19-gru-s-plan.jpg', 'https://explained.meme/assets/explained-19-gru-s-plan.jpg', 'meme', array['explained','editorial-reference','plan failure','presentation','realisation','film'], 'explained_editorial_reference:https://knowyourmeme.com/memes/grus-plan', 'A multi-panel plan looks sensible until the presenter reaches a step revealing that the plan defeats itself.', 'Despicable Me / Reddit (2018)', 'Automate the report. Spend six hours fixing the automation. Repeat every week. Wait.', now()),
  ('explained-20', 'I Am Once Again Asking', 'https://explained.meme/assets/explained-20-i-am-once-again-asking.jpg', 'https://explained.meme/assets/explained-20-i-am-once-again-asking.jpg', 'meme', array['explained','editorial-reference','request','politics','repetition','reaction'], 'explained_editorial_reference:https://time.com/5779804/bernie-sanders-memes/', 'A repeated request, appeal or demand framed as something the speaker has already asked for before.', 'Bernie Sanders campaign video / social media (2020)', 'I am once again asking you to name the final file final-final-v7.', now()),
  ('explained-22', 'Doge', 'https://explained.meme/assets/explained-22-doge.jpg', 'https://explained.meme/assets/explained-22-doge.jpg', 'meme', array['explained','editorial-reference','dog','Shiba Inu','inner monologue','image macro'], 'explained_editorial_reference:https://knowyourmeme.com/memes/doge', 'Uses a Shiba Inu photograph with fragmented inner-monologue captions such as “such,” “very” and “wow.”', 'Kabosu photograph / Tumblr (2010)', 'Such deadline. Very spreadsheet. Much panic. Wow.', now()),
  ('explained-23', 'Cheems', 'https://explained.meme/assets/explained-23-cheems.jpg', 'https://explained.meme/assets/explained-23-cheems.jpg', 'meme', array['explained','editorial-reference','dog','Shiba Inu','misspelling','Dogelore'], 'explained_editorial_reference:https://knowyourmeme.com/memes/cheems', 'A Shiba Inu character associated with deliberately misspelled words, especially inserting extra M sounds, and awkward or self-deprecating behaviour.', 'Balltze Instagram photograph / Dogelore (2019)', 'I will finish the documemt tommorrow.', now()),
  ('explained-25', 'UNO Draw 25', 'https://explained.meme/assets/explained-25-uno-draw-25.jpg', 'https://explained.meme/assets/explained-25-uno-draw-25.jpg', 'meme', array['explained','editorial-reference','dilemma','refusal','cards','object labelling'], 'explained_editorial_reference:https://knowyourmeme.com/memes/draw-25', 'Presents a simple action versus drawing 25 cards, implying that the person would rather accept an absurd penalty than do the action.', 'Twitter (2020)', 'Reply to the email now or draw 25.', now()),
  ('explained-26', 'Running Away Balloon', 'https://explained.meme/assets/explained-26-running-away-balloon.jpg', 'https://explained.meme/assets/explained-26-running-away-balloon.jpg', 'meme', array['explained','editorial-reference','obstacle','distraction','object labelling','webcomic'], 'explained_editorial_reference:https://knowyourmeme.com/memes/running-away-balloon', 'Shows somebody reaching for a goal while another force pulls them away, illustrating a limitation, distraction or obstacle.', 'Superelmer comic / Facebook (2017)', 'Me reaching for eight hours of sleep while one more episode pulls me back.', now()),
  ('explained-27', 'Always Has Been', 'https://explained.meme/assets/explained-27-always-has-been.jpg', 'https://explained.meme/assets/explained-27-always-has-been.jpg', 'meme', array['explained','editorial-reference','revelation','catchphrase','astronauts','exploitable'], 'explained_editorial_reference:https://knowyourmeme.com/memes/wait-its-all-ohio-always-has-been', 'A discovery is immediately confirmed by someone who already knew the truth, often with a dark or absurd threat.', '4chan / social media (2018)', 'Wait, the meeting could have been an email? Always has been.', now()),
  ('explained-29', 'They''re the Same Picture', 'https://explained.meme/assets/explained-29-they-re-the-same-picture.jpg', 'https://explained.meme/assets/explained-29-they-re-the-same-picture.jpg', 'meme', array['explained','editorial-reference','comparison','equivalence','television','reaction'], 'explained_editorial_reference:https://knowyourmeme.com/memes/theyre-the-same-picture', 'Declares two supposedly different choices, products or ideas effectively identical.', 'The Office / social media (2018)', 'Corporate asks you to compare unnecessary meeting and unnecessary call. They''re the same picture.', now()),
  ('explained-30', 'Left Exit 12 Off Ramp', 'https://explained.meme/assets/explained-30-left-exit-12-off-ramp.jpg', 'https://explained.meme/assets/explained-30-left-exit-12-off-ramp.jpg', 'meme', array['explained','editorial-reference','choice','distraction','driving','object labelling'], 'explained_editorial_reference:https://knowyourmeme.com/memes/left-exit-12-off-ramp', 'Shows someone abruptly abandoning the sensible route for a tempting or irrational alternative.', 'YouTube / Reddit (2017)', 'Finish the priority task; suddenly reorganise the entire desktop.', now()),
  ('explained-31', 'Bike Fall', 'https://explained.meme/assets/explained-31-bike-fall.jpg', 'https://explained.meme/assets/explained-31-bike-fall.jpg', 'meme', array['explained','editorial-reference','self-sabotage','blame','bicycle','comic'], 'explained_editorial_reference:https://knowyourmeme.com/memes/bike-fall', 'Blames another person or thing for a problem the subject clearly caused themselves.', 'Bâton Roue webcomic by Corentin Penloup / Tumblr-era circulation (2011)', 'Ignore every warning; system fails; blame the software.', now()),
  ('explained-32', 'Clown Makeup', 'https://explained.meme/assets/explained-32-clown-makeup.jpg', 'https://explained.meme/assets/explained-32-clown-makeup.jpg', 'meme', array['explained','editorial-reference','escalation','self-delusion','clown','progression'], 'explained_editorial_reference:https://knowyourmeme.com/memes/clown-makeup', 'Shows a person progressing through increasingly foolish decisions until they have fully made a clown of themselves.', 'Facebook (May 2019) / Twitter spread (June 2019)', 'Say yes to one meeting; accept six more; wonder why no work gets done.', now()),
  ('explained-33', 'Epic Handshake', 'https://explained.meme/assets/explained-33-epic-handshake.jpg', 'https://explained.meme/assets/explained-33-epic-handshake.jpg', 'meme', array['explained','editorial-reference','agreement','comparison','handshake','film'], 'explained_editorial_reference:https://knowyourmeme.com/memes/epic-handshake', 'Highlights common ground, a shared trait or agreement between two otherwise different groups.', 'Predator footage / YouTube (2007)', 'Morning people and night owls: both hate 8 a.m. meetings.', now()),
  ('explained-34', 'Sweating Jordan Peele', 'https://explained.meme/assets/explained-34-sweating-jordan-peele.jpg', 'https://explained.meme/assets/explained-34-sweating-jordan-peele.jpg', 'meme', array['explained','editorial-reference','pressure','nervousness','reaction','comedy'], 'explained_editorial_reference:https://knowyourmeme.com/memes/sweating-jordan-peele', 'Expresses extreme pressure, nervousness or panic when facing a difficult choice or discovery.', 'Key & Peele / reaction GIFs (2013)', 'When the client says, ‘Can you share your screen?’', now()),
  ('explained-35', 'Vince McMahon Reaction', 'https://explained.meme/assets/explained-35-vince-mcmahon-reaction.jpg', 'https://explained.meme/assets/explained-35-vince-mcmahon-reaction.jpg', 'meme', array['explained','editorial-reference','escalation','excitement','reaction','wrestling'], 'explained_editorial_reference:https://knowyourmeme.com/memes/vince-mcmahon-reaction', 'Escalates through several stages of excitement, approval or amazement.', 'YouTube / WWE footage (2013)', 'No meeting; email cancelled; deadline extended; Friday off.', now()),
  ('explained-36', 'Roll Safe', 'https://explained.meme/assets/explained-36-roll-safe.jpg', 'https://explained.meme/assets/explained-36-roll-safe.jpg', 'meme', array['explained','editorial-reference','bad logic','cleverness','reaction','television'], 'explained_editorial_reference:https://knowyourmeme.com/memes/roll-safe', 'Presents flawed reasoning as though it were a clever solution.', 'The Hood Documentary / Twitter (2016)', 'You cannot miss a deadline if you never set one.', now()),
  ('explained-37', 'Arthur Fist', 'https://explained.meme/assets/explained-37-arthur-fist.jpg', 'https://explained.meme/assets/explained-37-arthur-fist.jpg', 'meme', array['explained','editorial-reference','anger','frustration','reaction','cartoon'], 'explained_editorial_reference:https://knowyourmeme.com/memes/arthurs-fist', 'Represents controlled anger, frustration or the effort to remain calm.', 'Arthur / Twitter (2016)', 'When someone replies all to say ‘thanks.’', now()),
  ('explained-38', 'Confused Nick Young', 'https://explained.meme/assets/explained-38-confused-nick-young.jpg', 'https://explained.meme/assets/explained-38-confused-nick-young.jpg', 'meme', array['explained','editorial-reference','confusion','disbelief','reaction','interview'], 'explained_editorial_reference:https://knowyourmeme.com/memes/confused-nick-young', 'Reacts to a baffling, contradictory or nonsensical statement.', 'Through the Lens / YouTube (2014)', 'The project is urgent, but nobody has approved it.', now()),
  ('explained-39', 'Blinking White Guy', 'https://explained.meme/assets/explained-39-blinking-white-guy.jpg', 'https://explained.meme/assets/explained-39-blinking-white-guy.jpg', 'meme', array['explained','editorial-reference','disbelief','surprise','reaction','GIF'], 'explained_editorial_reference:https://knowyourmeme.com/memes/blinking-white-guy', 'Shows disbelief or surprise after hearing something absurd or unexpected.', 'NeoGAF / Giant Bomb footage (2015)', 'You want the report today, but the data arrives tomorrow?', now()),
  ('explained-40', 'Michael Scott No God Please No', 'https://explained.meme/assets/explained-40-michael-scott-no-god-please-no.jpg', 'https://explained.meme/assets/explained-40-michael-scott-no-god-please-no.jpg', 'meme', array['explained','editorial-reference','rejection','dread','reaction','television'], 'explained_editorial_reference:https://knowyourmeme.com/memes/michael-scott-no-god-please-no', 'Expresses intense rejection, dread or horror at something happening again.', 'The Office, “Frame Toby” (2008)', 'Another mandatory team-building workshop? No, God, please no.', now()),
  ('explained-41', 'Oprah You Get a Car', 'https://explained.meme/assets/explained-41-oprah-you-get-a-car.jpg', 'https://explained.meme/assets/explained-41-oprah-you-get-a-car.jpg', 'meme', array['explained','editorial-reference','distribution','giveaway','reaction','television'], 'explained_editorial_reference:https://knowyourmeme.com/memes/oprah-you-get-a-car', 'Shows something being distributed freely or indiscriminately to everyone.', 'The Oprah Winfrey Show footage / YouTube (2008)', 'You get a meeting, you get a meeting, everybody gets a meeting.', now()),
  ('explained-42', 'Leonardo DiCaprio Cheers', 'https://explained.meme/assets/explained-42-leonardo-dicaprio-cheers.jpg', 'https://explained.meme/assets/explained-42-leonardo-dicaprio-cheers.jpg', 'meme', array['explained','editorial-reference','approval','toast','reaction','film'], 'explained_editorial_reference:https://knowyourmeme.com/memes/leonardo-dicaprio-cheers', 'Signals recognition, approval, congratulations or a knowing toast.', 'The Great Gatsby (2013)', 'The spreadsheet balances on the first attempt. Cheers.', now()),
  ('explained-43', 'Leonardo DiCaprio Laughing', 'https://explained.meme/assets/explained-43-leonardo-dicaprio-laughing.jpg', 'https://explained.meme/assets/explained-43-leonardo-dicaprio-laughing.jpg', 'meme', array['explained','editorial-reference','laughter','mockery','reaction','film'], 'explained_editorial_reference:https://knowyourmeme.com/memes/leonardo-dicaprio-laughing', 'Shows delighted, mocking or disbelieving laughter at another person''s claim.', 'Django Unchained footage / Tumblr (2017)', '‘It will only be a five-minute meeting.’', now()),
  ('explained-44', 'Sad Pablo Escobar', 'https://explained.meme/assets/explained-44-sad-pablo-escobar.jpg', 'https://explained.meme/assets/explained-44-sad-pablo-escobar.jpg', 'meme', array['explained','editorial-reference','waiting','loneliness','boredom','television'], 'explained_editorial_reference:https://knowyourmeme.com/memes/pablo-escobar-waiting', 'Represents lonely waiting, boredom or having nothing to do.', 'Narcos season 2 footage / social media (2016)', 'Waiting for someone to approve the final draft.', now()),
  ('explained-45', 'Waiting Skeleton', 'https://explained.meme/assets/explained-45-waiting-skeleton.jpg', 'https://explained.meme/assets/explained-45-waiting-skeleton.jpg', 'meme', array['explained','editorial-reference','waiting','delay','skeleton','reaction'], 'explained_editorial_reference:https://knowyourmeme.com/memes/waiting-for-op', 'Exaggerates how long someone has been waiting for an event, reply or result.', 'Meme Generator “Waiting for OP” image macro (2010)', 'Me waiting for the ‘quick’ software update to finish.', now()),
  ('explained-46', 'Confused Travolta', 'https://explained.meme/assets/explained-46-confused-travolta.jpg', 'https://explained.meme/assets/explained-46-confused-travolta.jpg', 'meme', array['explained','editorial-reference','confusion','searching','reaction','film'], 'explained_editorial_reference:https://knowyourmeme.com/memes/confused-travolta', 'Shows someone looking around in confusion because something or somebody is missing.', 'Pulp Fiction footage / Imgur (2015)', 'Opening the shared folder after someone says the file is definitely there.', now()),
  ('explained-47', 'Spider-Man Pointing', 'https://explained.meme/assets/explained-47-spider-man-pointing.jpg', 'https://explained.meme/assets/explained-47-spider-man-pointing.jpg', 'meme', array['explained','editorial-reference','comparison','duplication','accusation','cartoon'], 'explained_editorial_reference:https://knowyourmeme.com/memes/spider-man-pointing-at-spider-man', 'Compares two nearly identical people or groups accusing or recognising each other.', 'Spider-Man animated series / Sharenator (2011)', 'Marketing blaming Sales; Sales blaming Marketing.', now()),
  ('explained-48', 'Batman Slapping Robin', 'https://explained.meme/assets/explained-48-batman-slapping-robin.jpg', 'https://explained.meme/assets/explained-48-batman-slapping-robin.jpg', 'meme', array['explained','editorial-reference','dialogue','interruption','correction','comic'], 'explained_editorial_reference:https://knowyourmeme.com/memes/batman-slapping-robin', 'A blunt interruption or correction delivered before the other person can finish speaking.', 'World’s Finest Comics #153 (1965) / image-macro circulation (late 2000s)', 'Robin: Let’s add another feature— Batman: Ship the current version.', now()),
  ('explained-49', 'Trollface', 'https://explained.meme/assets/explained-49-trollface.jpg', 'https://explained.meme/assets/explained-49-trollface.jpg', 'meme', array['explained','editorial-reference','trolling','character','reaction','rage comic'], 'explained_editorial_reference:https://knowyourmeme.com/memes/trollface', 'Signals deliberate trolling, provocation or satisfaction after causing annoyance.', 'DeviantArt (2008)', 'Changes the group-chat name and waits for the notifications.', now()),
  ('explained-50', 'Grumpy Cat', 'https://explained.meme/assets/explained-50-grumpy-cat.jpg', 'https://explained.meme/assets/explained-50-grumpy-cat.jpg', 'meme', array['explained','editorial-reference','cat','displeasure','reaction','character'], 'explained_editorial_reference:https://knowyourmeme.com/memes/grumpy-cat', 'Expresses persistent displeasure, pessimism or rejection.', 'Reddit (2012)', 'Team celebration scheduled for 8 a.m. No.', now()),
  ('explained-51', 'Nyan Cat', 'https://explained.meme/assets/explained-51-nyan-cat.jpg', 'https://explained.meme/assets/explained-51-nyan-cat.jpg', 'meme', array['explained','editorial-reference','cat','pixel art','rainbow','internet classic'], 'explained_editorial_reference:https://knowyourmeme.com/memes/nyan-cat-pop-tart-cat', 'A flying pixel cat with a rainbow trail, used as a playful symbol of early internet absurdity.', 'LOL-COMICS (2011)', 'The report is late, but at least the loading animation is cheerful.', now()),
  ('explained-52', 'Keyboard Cat', 'https://explained.meme/assets/explained-52-keyboard-cat.jpg', 'https://explained.meme/assets/explained-52-keyboard-cat.jpg', 'meme', array['explained','editorial-reference','cat','failure','outro','video'], 'explained_editorial_reference:https://knowyourmeme.com/memes/keyboard-cat', 'A cat playing a keyboard, often used as a humorous outro after failure or embarrassment.', 'YouTube (2009)', 'Presentation crashes on the final slide. Play him off, Keyboard Cat.', now()),
  ('explained-53', 'Dramatic Chipmunk', 'https://explained.meme/assets/explained-53-dramatic-chipmunk.jpg', 'https://explained.meme/assets/explained-53-dramatic-chipmunk.jpg', 'meme', array['explained','editorial-reference','dramatic reveal','reaction','animal','video'], 'explained_editorial_reference:https://knowyourmeme.com/memes/dramatic-chipmunk', 'A sudden dramatic turn toward the camera that exaggerates a reveal or accusation.', 'YouTube (2007)', 'Someone mentions the missing budget line. Dramatic turn.', now()),
  ('explained-54', 'Ermahgerd', 'https://explained.meme/assets/explained-54-ermahgerd.jpg', 'https://explained.meme/assets/explained-54-ermahgerd.jpg', 'meme', array['explained','editorial-reference','excitement','character macro','books','pronunciation'], 'explained_editorial_reference:https://knowyourmeme.com/memes/ermahgerd', 'Represents overwhelming nerdy excitement using deliberately distorted pronunciation.', 'Reddit (2012)', 'Ermahgerd, the meeting was cancelled!', now()),
  ('explained-55', 'Overly Attached Girlfriend', 'https://explained.meme/assets/explained-55-overly-attached-girlfriend.jpg', 'https://explained.meme/assets/explained-55-overly-attached-girlfriend.jpg', 'meme', array['explained','editorial-reference','obsession','character macro','relationship','video'], 'explained_editorial_reference:https://knowyourmeme.com/memes/overly-attached-girlfriend', 'Portrays obsessive, possessive or uncomfortably intense attention.', 'YouTube (2012)', 'You said you were busy, so I checked all twelve status indicators.', now()),
  ('explained-56', 'Scumbag Steve', 'https://explained.meme/assets/explained-56-scumbag-steve.jpg', 'https://explained.meme/assets/explained-56-scumbag-steve.jpg', 'meme', array['explained','editorial-reference','selfishness','character macro','advice animal','behaviour'], 'explained_editorial_reference:https://knowyourmeme.com/memes/scumbag-steve', 'Labels inconsiderate, selfish or socially obnoxious behaviour.', 'Reddit (2011)', 'Borrows your charger; returns only the cable.', now()),
  ('explained-57', 'Condescending Wonka', 'https://explained.meme/assets/explained-57-condescending-wonka.jpg', 'https://explained.meme/assets/explained-57-condescending-wonka.jpg', 'meme', array['explained','editorial-reference','sarcasm','condescension','reaction','film'], 'explained_editorial_reference:https://knowyourmeme.com/memes/condescending-wonka-creepy-wonka', 'Pairs a patronising reaction with sarcastic disbelief about somebody''s claim.', 'Quickmeme (2010)', 'You finished one task early? Please, tell me more about productivity.', now()),
  ('explained-58', 'The Most Interesting Man in the World', 'https://explained.meme/assets/explained-58-the-most-interesting-man-in-the-world.jpg', 'https://explained.meme/assets/explained-58-the-most-interesting-man-in-the-world.jpg', 'meme', array['explained','editorial-reference','statement','advertising','character macro','catchphrase'], 'explained_editorial_reference:https://knowyourmeme.com/memes/the-most-interesting-man-in-the-world', 'Uses the structure ‘I don''t always X, but when I do, Y’ for an exaggerated personal rule.', 'Dos Equis television commercial (2007)', 'I don''t always join meetings, but when I do, they could have been emails.', now()),
  ('explained-59', 'First World Problems', 'https://explained.meme/assets/explained-59-first-world-problems.jpg', 'https://explained.meme/assets/explained-59-first-world-problems.jpg', 'meme', array['explained','editorial-reference','minor problem','privilege','character macro','complaint'], 'explained_editorial_reference:https://knowyourmeme.com/memes/first-world-problems', 'Mocks minor inconveniences experienced from a position of comfort or privilege.', 'Unknown / image-macro culture (2011)', 'The Wi-Fi reaches the sofa but not the garden chair.', now()),
  ('explained-60', 'Salt Bae', 'https://explained.meme/assets/explained-60-salt-bae.jpg', 'https://explained.meme/assets/explained-60-salt-bae.jpg', 'meme', array['explained','editorial-reference','flair','finishing touch','reaction','video'], 'explained_editorial_reference:https://knowyourmeme.com/memes/salt-bae', 'Shows someone adding a final touch with excessive flair or theatrical confidence.', 'Twitter (2017)', 'Adds one emoji to the quarterly report. Salt Bae.', now()),
  ('explained-61', 'Kermit Sipping Tea', 'https://explained.meme/assets/explained-61-kermit-sipping-tea.jpg', 'https://explained.meme/assets/explained-61-kermit-sipping-tea.jpg', 'meme', array['explained','editorial-reference','commentary','gossip','reaction','advertising'], 'explained_editorial_reference:https://knowyourmeme.com/memes/kermit-sipping-tea', 'Makes a pointed observation while pretending it is none of the speaker''s business.', 'Lipton “Be More Tea” advertisement / Instagram (2014)', 'Somebody deleted the backup, but that''s none of my business.', now()),
  ('explained-62', 'Evil Kermit', 'https://explained.meme/assets/explained-62-evil-kermit.jpg', 'https://explained.meme/assets/explained-62-evil-kermit.jpg', 'meme', array['explained','editorial-reference','temptation','inner conflict','dialogue','film'], 'explained_editorial_reference:https://knowyourmeme.com/memes/evil-kermit', 'Shows an internal struggle where a bad inner voice encourages temptation or irresponsible behaviour.', 'Twitter (2016)', 'Me: save the document. Evil me: close it and trust autosave.', now()),
  ('explained-63', 'Sad Keanu', 'https://explained.meme/assets/explained-63-sad-keanu.jpg', 'https://explained.meme/assets/explained-63-sad-keanu.jpg', 'meme', array['explained','editorial-reference','sadness','loneliness','reaction','celebrity'], 'explained_editorial_reference:https://knowyourmeme.com/memes/sad-keanu', 'Represents loneliness, sadness or quietly eating alone.', 'Reddit (2010)', 'When everyone is working from home except you.', now()),
  ('explained-64', 'Side-Eyeing Chloe', 'https://explained.meme/assets/explained-64-side-eyeing-chloe.jpg', 'https://explained.meme/assets/explained-64-side-eyeing-chloe.jpg', 'meme', array['explained','editorial-reference','suspicion','awkwardness','reaction','video'], 'explained_editorial_reference:https://knowyourmeme.com/memes/side-eyeing-chloe', 'A suspicious or uncomfortable side-eye used when something sounds strange or unconvincing.', 'YouTube footage / Tumblr (2013)', 'Manager: this reorganisation will simplify everything. Chloe side-eye.', now()),
  ('explained-65', 'Kombucha Girl', 'https://explained.meme/assets/explained-65-kombucha-girl.jpg', 'https://explained.meme/assets/explained-65-kombucha-girl.jpg', 'meme', array['explained','editorial-reference','evaluation','reaction','TikTok','mixed feelings'], 'explained_editorial_reference:https://knowyourmeme.com/memes/kombucha-girl', 'Shows a rapid shift between dislike and tentative approval while evaluating something.', 'TikTok video by Brittany Broski (August 2019)', 'A four-day workweek? At first unsure… actually, yes.', now()),
  ('explained-66', 'Confused Math Lady', 'https://explained.meme/assets/explained-66-confused-math-lady.jpg', 'https://explained.meme/assets/explained-66-confused-math-lady.jpg', 'meme', array['explained','editorial-reference','confusion','calculation','reaction','television'], 'explained_editorial_reference:https://knowyourmeme.com/memes/confused-math-lady', 'Visualises intense confusion or mental calculation in response to something difficult to understand.', 'Senhora do Destino footage / UKMix (2013)', 'Trying to understand how five small tasks became forty hours of work.', now()),
  ('explained-67', 'Crying Jordan', 'https://explained.meme/assets/explained-67-crying-jordan.jpg', 'https://explained.meme/assets/explained-67-crying-jordan.jpg', 'meme', array['explained','editorial-reference','defeat','disappointment','reaction','sports'], 'explained_editorial_reference:https://knowyourmeme.com/memes/crying-michael-jordan', 'Places Michael Jordan''s crying face onto people or things experiencing defeat or disappointment.', 'Hall of Fame speech (2009)', 'My weekend plans after seeing Monday''s deadline.', now()),
  ('explained-68', 'Ight Imma Head Out', 'https://explained.meme/assets/explained-68-ight-imma-head-out.jpg', 'https://explained.meme/assets/explained-68-ight-imma-head-out.jpg', 'meme', array['explained','editorial-reference','exit','reaction','cartoon','departure'], 'explained_editorial_reference:https://knowyourmeme.com/memes/ight-imma-head-out', 'Signals an immediate decision to leave after hearing or seeing something undesirable.', 'Twitter (2019)', 'The meeting has no agenda? Ight, imma head out.', now()),
  ('explained-69', 'Patrick Wallet', 'https://explained.meme/assets/explained-69-patrick-wallet.jpg', 'https://explained.meme/assets/explained-69-patrick-wallet.jpg', 'meme', array['explained','editorial-reference','dialogue','failed reasoning','frustration','cartoon'], 'explained_editorial_reference:https://knowyourmeme.com/memes/patrick-stars-wallet', 'A dialogue where clear logic repeatedly fails to persuade someone who refuses the obvious conclusion.', 'SpongeBob SquarePants footage / Imgur (2013)', 'You asked for the report. This is the report. So you received it? No.', now()),
  ('explained-70', 'Caveman SpongeBob', 'https://explained.meme/assets/explained-70-caveman-spongebob.jpg', 'https://explained.meme/assets/explained-70-caveman-spongebob.jpg', 'meme', array['explained','editorial-reference','panic','primitive reaction','cartoon','threat'], 'explained_editorial_reference:https://knowyourmeme.com/memes/spongegar-primitive-sponge-caveman-spongebob', 'Represents primitive panic, sudden threat detection or an instinctive overreaction.', 'SpongeBob SquarePants footage / 4chan (2015)', 'Hearing the email notification after logging off.', now()),
  ('explained-71', 'Mr. Krabs Blur', 'https://explained.meme/assets/explained-71-mr-krabs-blur.jpg', 'https://explained.meme/assets/explained-71-mr-krabs-blur.jpg', 'meme', array['explained','editorial-reference','disorientation','panic','reaction','cartoon'], 'explained_editorial_reference:https://knowyourmeme.com/memes/confused-mr-krabs', 'Shows disorientation, panic or sensory overload in a chaotic situation.', 'SpongeBob SquarePants footage / Twitter (2016)', 'When three people ask questions while your screen is sharing.', now()),
  ('explained-72', 'SpongeBob Imagination Rainbow', 'https://explained.meme/assets/explained-72-spongebob-imagination-rainbow.jpg', 'https://explained.meme/assets/explained-72-spongebob-imagination-rainbow.jpg', 'meme', array['explained','editorial-reference','imagination','irony','statement','cartoon'], 'explained_editorial_reference:https://knowyourmeme.com/memes/spongebob-imagination', 'Adds an ironic or enthusiastic label to something being imagined or exaggerated.', 'SpongeBob SquarePants, “Idiot Box” (2002) / image-macro culture', 'Imagine… documentation that is actually current.', now()),
  ('explained-73', 'Anakin and Padmé Four-Panel', 'https://explained.meme/assets/explained-73-anakin-and-padme-four-panel.jpg', 'https://explained.meme/assets/explained-73-anakin-and-padme-four-panel.jpg', 'meme', array['explained','editorial-reference','dialogue','expectation','silence','film'], 'explained_editorial_reference:https://knowyourmeme.com/memes/for-the-better-right', 'Starts with an optimistic assumption and ends with uneasy silence when reassurance never comes.', 'Star Wars footage / Twitter (2021)', 'You tested the backup, right? You tested it, right?', now()),
  ('explained-74', 'It''s Over Anakin, I Have the High Ground', 'https://explained.meme/assets/explained-74-it-s-over-anakin-i-have-the-high-ground.jpg', 'https://explained.meme/assets/explained-74-it-s-over-anakin-i-have-the-high-ground.jpg', 'meme', array['explained','editorial-reference','advantage','dialogue','film','overconfidence'], 'explained_editorial_reference:https://knowyourmeme.com/memes/its-over-anakin-i-have-the-high-ground', 'Claims a decisive advantage, often followed by overconfidence or a failed challenge.', 'Star Wars: Episode III – Revenge of the Sith (2005)', 'I have the approved version. You underestimate my duplicate files.', now()),
  ('explained-75', 'Thanos: What Did It Cost?', 'https://explained.meme/assets/explained-75-thanos-what-did-it-cost.jpg', 'https://explained.meme/assets/explained-75-thanos-what-did-it-cost.jpg', 'meme', array['explained','editorial-reference','sacrifice','dialogue','success','film'], 'explained_editorial_reference:https://knowyourmeme.com/memes/what-did-it-cost-everything', 'Pairs an achievement with the painful sacrifice required to obtain it.', 'Avengers: Infinity War (2018)', 'Inbox zero. What did it cost? The entire afternoon.', now()),
  ('explained-76', 'Captain America Elevator', 'https://explained.meme/assets/explained-76-captain-america-elevator.jpg', 'https://explained.meme/assets/explained-76-captain-america-elevator.jpg', 'meme', array['explained','editorial-reference','tension','recognition','reaction','film'], 'explained_editorial_reference:https://knowyourmeme.com/memes/captain-america-elevator-fight', 'Represents rising tension, recognising danger or calmly preparing for a confrontation.', 'Marvel film footage / Instagram (2019)', 'When the meeting title says ‘quick alignment’ and Legal joins.', now()),
  ('explained-77', 'Ralph Wiggum: I''m in Danger', 'https://explained.meme/assets/explained-77-ralph-wiggum-i-m-in-danger.jpg', 'https://explained.meme/assets/explained-77-ralph-wiggum-i-m-in-danger.jpg', 'meme', array['explained','editorial-reference','danger','reaction','cartoon','understatement'], 'explained_editorial_reference:https://knowyourmeme.com/memes/ralph-in-danger-im-in-danger', 'Calmly acknowledges that a situation is obviously becoming dangerous or disastrous.', 'Family Guy/The Simpsons crossover “The Simpsons Guy” (2014)', 'Deploying on Friday afternoon: I''m in danger.', now()),
  ('explained-78', 'Homer Disappearing into Bushes', 'https://explained.meme/assets/explained-78-homer-disappearing-into-bushes.jpg', 'https://explained.meme/assets/explained-78-homer-disappearing-into-bushes.jpg', 'meme', array['explained','editorial-reference','exit','embarrassment','reaction','cartoon'], 'explained_editorial_reference:https://knowyourmeme.com/memes/homer-simpson-backs-into-bushes', 'Shows an embarrassed retreat or quietly withdrawing from an awkward situation.', 'The Simpsons / GIF culture (2010)', 'Volunteers an idea; realises it means more work; disappears.', now()),
  ('explained-79', 'Principal Skinner: Pathetic', 'https://explained.meme/assets/explained-79-principal-skinner-pathetic.jpg', 'https://explained.meme/assets/explained-79-principal-skinner-pathetic.jpg', 'meme', array['explained','editorial-reference','dismissal','judgement','reaction','cartoon'], 'explained_editorial_reference:https://knowyourmeme.com/memes/principal-skinners-pathetic', 'A dismissive judgement aimed at a weak attempt or unimpressive result.', 'The Simpsons footage / Tumblr (2016)', 'The password is still ‘password1’? Pathetic.', now()),
  ('explained-80', 'Lisa Simpson Presentation', 'https://explained.meme/assets/explained-80-lisa-simpson-presentation.jpg', 'https://explained.meme/assets/explained-80-lisa-simpson-presentation.jpg', 'meme', array['explained','editorial-reference','opinion','presentation','statement','cartoon'], 'explained_editorial_reference:https://knowyourmeme.com/memes/lisa-simpsons-presentation', 'Uses a presentation screen to state an opinion, argument or uncomfortable truth.', 'The Simpsons footage / Reddit (2018)', 'More meetings do not fix unclear decisions.', now()),
  ('explained-81', 'Grandpa Simpson Walks In and Out', 'https://explained.meme/assets/explained-81-grandpa-simpson-walks-in-and-out.jpg', 'https://explained.meme/assets/explained-81-grandpa-simpson-walks-in-and-out.jpg', 'meme', array['explained','editorial-reference','exit','reversal','reaction','cartoon'], 'explained_editorial_reference:https://knowyourmeme.com/memes/grandpa-simpson-walks-in-and-out', 'Shows immediately reversing course and leaving after seeing an undesirable situation.', 'The Simpsons, “Bart After Dark” (1996) / looping GIF culture', 'Joins call; hears ‘icebreaker’; turns around.', now()),
  ('explained-82', 'Who Killed Hannibal?', 'https://explained.meme/assets/explained-82-who-killed-hannibal.jpg', 'https://explained.meme/assets/explained-82-who-killed-hannibal.jpg', 'meme', array['explained','editorial-reference','self-sabotage','blame','television','dialogue'], 'explained_editorial_reference:https://knowyourmeme.com/memes/who-killed-hannibal', 'Shows someone causing a problem and then blaming an unrelated person or group for it.', 'The Eric Andre Show footage (2013) / viral image-macro spread (2018)', 'Removes the deadline, project runs late: Who could have caused this?', now()),
  ('explained-83', 'I Guess I''ll Die', 'https://explained.meme/assets/explained-83-i-guess-i-ll-die.jpg', 'https://explained.meme/assets/explained-83-i-guess-i-ll-die.jpg', 'meme', array['explained','editorial-reference','resignation','reaction','webcomic','inconvenience'], 'explained_editorial_reference:https://knowyourmeme.com/memes/i-guess-ill-die', 'A resigned response to a small inconvenience presented as though no alternative exists.', 'Stock photograph of Mike Baldwin / reaction-image circulation (2016)', 'The coffee machine is empty. I guess I''ll die.', now()),
  ('explained-84', 'Tuxedo Winnie the Pooh', 'https://explained.meme/assets/explained-84-tuxedo-winnie-the-pooh.jpg', 'https://explained.meme/assets/explained-84-tuxedo-winnie-the-pooh.jpg', 'meme', array['explained','editorial-reference','comparison','refined','wording','cartoon'], 'explained_editorial_reference:https://knowyourmeme.com/memes/tuxedo-winnie-the-pooh', 'Compares an ordinary expression or choice with a supposedly refined, formal alternative.', 'Winnie the Pooh and Tigger Too (1974) / 4chan and Reddit spread (2019)', 'Problem. Issue. Strategic opportunity.', now()),
  ('explained-85', 'Bell Curve / IQ Distribution', 'https://explained.meme/assets/explained-85-bell-curve-iq-distribution.jpg', 'https://explained.meme/assets/explained-85-bell-curve-iq-distribution.jpg', 'meme', array['explained','editorial-reference','comparison','intelligence','bell curve','overthinking'], 'explained_editorial_reference:https://knowyourmeme.com/memes/iq-bell-curve-midwit', 'Shows two extremes reaching the same simple conclusion while the middle overcomplicates it.', '4chan “midwit” format (2017); Wojak bell-curve variant popularised later', 'Beginner: save the file. Expert: save the file. Middle: build a twelve-step sync workflow.', now()),
  ('explained-86', 'Hard to Swallow Pills', 'https://explained.meme/assets/explained-86-hard-to-swallow-pills.jpg', 'https://explained.meme/assets/explained-86-hard-to-swallow-pills.jpg', 'meme', array['explained','editorial-reference','uncomfortable truth','opinion','pill','webcomic'], 'explained_editorial_reference:https://knowyourmeme.com/memes/hard-to-swallow-pills', 'Labels an uncomfortable fact as medicine that is difficult but necessary to accept.', 'WikiHow stock illustrations (2017) / Reddit spread (2018)', 'Busy is not the same as productive.', now()),
  ('explained-87', 'Nobody:', 'https://explained.meme/assets/explained-87-nobody.jpg', 'https://explained.meme/assets/explained-87-nobody.jpg', 'meme', array['explained','editorial-reference','unprompted behaviour','text format','silence','reaction'], 'explained_editorial_reference:https://knowyourmeme.com/memes/nobody', 'Frames an action as completely unprompted by showing that nobody asked for it.', 'Twitter “Literally Nobody” format (2018)', 'Nobody: Absolutely nobody: Printer: low cyan, cannot print black.', now()),
  ('explained-88', 'Panik Kalm Panik', 'https://explained.meme/assets/explained-88-panik-kalm-panik.jpg', 'https://explained.meme/assets/explained-88-panik-kalm-panik.jpg', 'meme', array['explained','editorial-reference','escalation','panic','relief','Meme Man'], 'explained_editorial_reference:https://knowyourmeme.com/memes/panik-kalm-panik', 'Moves from panic to relief and back to panic when new information changes the situation.', 'Meme Man format / Reddit (February 2020)', 'Deadline today. Panik. Extension granted. Kalm. Extension is ten minutes. Panik.', now()),
  ('explained-89', 'Stonks', 'https://explained.meme/assets/explained-89-stonks.jpg', 'https://explained.meme/assets/explained-89-stonks.jpg', 'meme', array['explained','editorial-reference','ironic success','finance','Meme Man','reaction'], 'explained_editorial_reference:https://knowyourmeme.com/memes/stonks', 'Ironic approval of a foolish financial or strategic decision presented as profit or success.', 'Special Meme Fresh / Facebook (June 2017)', 'Spend €20 to avoid a €5 delivery fee. Stonks.', now()),
  ('explained-90', 'American Chopper Argument', 'https://explained.meme/assets/explained-90-american-chopper-argument.jpg', 'https://explained.meme/assets/explained-90-american-chopper-argument.jpg', 'meme', array['explained','editorial-reference','argument','dialogue','television','escalation'], 'explained_editorial_reference:https://knowyourmeme.com/memes/american-chopper-argument', 'Turns a disagreement into an escalating multi-panel shouting match.', 'American Chopper footage (2009); viral Twitter format (2018)', 'We need fewer meetings. Let''s schedule a meeting to discuss it.', now()),
  ('explained-91', 'Gigachad', 'https://explained.meme/assets/explained-91-gigachad.jpg', 'https://explained.meme/assets/explained-91-gigachad.jpg', 'meme', array['explained','editorial-reference','confidence','character','physique','reaction'], 'explained_editorial_reference:https://knowyourmeme.com/memes/gigachad', 'Represents an exaggerated ideal of confidence, strength or unapologetic self-assurance.', 'Sleek’N’Tears photography by Krista Sudmalis / 4chan (2017)', 'Reads the instructions before starting. Gigachad.', now()),
  ('explained-92', 'Virgin vs. Chad', 'https://explained.meme/assets/explained-92-virgin-vs-chad.jpg', 'https://explained.meme/assets/explained-92-virgin-vs-chad.jpg', 'meme', array['explained','editorial-reference','comparison','character','confidence','drawing'], 'explained_editorial_reference:https://knowyourmeme.com/memes/virgin-vs-chad', 'Contrasts an insecure or overcomplicated character with a confident, exaggerated counterpart.', '4chan /r9k/ (2017)', 'Virgin twelve-tab workflow vs. Chad single checklist.', now()),
  ('explained-93', 'Wojak', 'https://explained.meme/assets/explained-93-wojak.jpg', 'https://explained.meme/assets/explained-93-wojak.jpg', 'meme', array['explained','editorial-reference','character','reaction','drawing','emotion'], 'explained_editorial_reference:https://knowyourmeme.com/memes/wojak-feels-guy', 'A simple drawn character used to express melancholy, frustration, nostalgia and many other emotions.', 'Polish imageboard Vichan (2009) / Krautchan (2010)', 'Says ‘no worries’ after receiving the fourth revision request.', now()),
  ('explained-94', 'NPC Wojak', 'https://explained.meme/assets/explained-94-npc-wojak.jpg', 'https://explained.meme/assets/explained-94-npc-wojak.jpg', 'meme', array['explained','editorial-reference','conformity','scripted behaviour','character','drawing'], 'explained_editorial_reference:https://knowyourmeme.com/memes/npc-wojak', 'Portrays somebody as conformist, repetitive or following a script without independent thought.', '4chan (2016); mainstream political spread (2018)', 'Every consultant slide: leverage synergies, unlock value, transform.', now()),
  ('explained-95', 'Soyjak Pointing', 'https://explained.meme/assets/explained-95-soyjak-pointing.jpg', 'https://explained.meme/assets/explained-95-soyjak-pointing.jpg', 'meme', array['explained','editorial-reference','excitement','pointing','character','reaction'], 'explained_editorial_reference:https://knowyourmeme.com/memes/two-soyjaks-pointing', 'Shows exaggerated excitement or recognition, often mockingly aimed at shallow enthusiasm.', 'John Oberg photograph / Twitter (February 2020); Soyjak adaptation later in 2020', 'Look! The app changed the button colour!', now()),
  ('explained-96', 'Pepe the Frog', 'https://explained.meme/assets/explained-96-pepe-the-frog.jpg', 'https://explained.meme/assets/explained-96-pepe-the-frog.jpg', 'meme', array['explained','editorial-reference','frog','reaction','character','context risk'], 'explained_editorial_reference:https://knowyourmeme.com/memes/pepe-the-frog', 'A highly adaptable cartoon frog used for reactions ranging from sadness to smugness; later contexts can carry political baggage.', 'Boy’s Club comic by Matt Furie / Myspace (2005)', 'Feels good when the meeting ends early.', now()),
  ('explained-97', 'Elmo Fire', 'https://explained.meme/assets/explained-97-elmo-fire.jpg', 'https://explained.meme/assets/explained-97-elmo-fire.jpg', 'meme', array['explained','editorial-reference','chaos','fire','reaction','television'], 'explained_editorial_reference:https://knowyourmeme.com/memes/elmo-rise', 'Represents gleeful chaos, destruction or extreme excitement as flames rise behind Elmo.', 'Elmo cake image on CakeWrecks (2012) / fire edit on Tumblr (2014)', 'Production is down, but the dashboard is green. Elmo fire.', now()),
  ('explained-98', 'Pedro Pascal Laughing/Crying', 'https://explained.meme/assets/explained-98-pedro-pascal-laughing-crying.jpg', 'https://explained.meme/assets/explained-98-pedro-pascal-laughing-crying.jpg', 'meme', array['explained','editorial-reference','mixed emotion','laughter','crying','film'], 'explained_editorial_reference:https://knowyourmeme.com/memes/pedro-pascal-laughing-then-crying', 'Shows something that is simultaneously hilarious and emotionally painful.', 'Cape Cod Theatre Project virtual benefit reading (2020); viral edits (2021)', 'The bug is caused by the fix for the previous bug.', now()),
  ('explained-99', 'Kevin James Smirking', 'https://explained.meme/assets/explained-99-kevin-james-smirking.jpg', 'https://explained.meme/assets/explained-99-kevin-james-smirking.jpg', 'meme', array['explained','editorial-reference','awkwardness','smirk','reaction','television'], 'explained_editorial_reference:https://knowyourmeme.com/memes/kevin-james-smirking', 'Expresses awkward self-consciousness, mild guilt or being caught in an uncomfortable moment.', 'The King of Queens promotional photograph (1998) / X (2023)', 'When they ask who changed the shared spreadsheet.', now()),
  ('explained-100', 'Chill Guy', 'https://explained.meme/assets/explained-100-chill-guy.jpg', 'https://explained.meme/assets/explained-100-chill-guy.jpg', 'meme', array['explained','editorial-reference','calm','indifference','character','drawing'], 'explained_editorial_reference:https://knowyourmeme.com/memes/chill-guy', 'Represents remaining relaxed, detached or unbothered despite pressure or conflict.', 'Artwork by Phillip Banks / Twitter (October 2023); viral on TikTok (2024)', 'Deadline moved forward, but he''s just a chill guy.', now())
on conflict (id) do update set
  title = excluded.title,
  image_url = excluded.image_url,
  image_uri = excluded.image_uri,
  kind = excluded.kind,
  tags = excluded.tags,
  source = excluded.source,
  meaning = excluded.meaning,
  origin = excluded.origin,
  example = excluded.example;

do $$
begin
  if (select count(*) from public.memes where id in (
    'explained-18','explained-19','explained-20','explained-22','explained-23','explained-25','explained-26','explained-27','explained-29','explained-30','explained-31','explained-32','explained-33','explained-34','explained-35','explained-36','explained-37','explained-38','explained-39','explained-40','explained-41','explained-42','explained-43','explained-44','explained-45','explained-46','explained-47','explained-48','explained-49','explained-50','explained-51','explained-52','explained-53','explained-54','explained-55','explained-56','explained-57','explained-58','explained-59','explained-60','explained-61','explained-62','explained-63','explained-64','explained-65','explained-66','explained-67','explained-68','explained-69','explained-70','explained-71','explained-72','explained-73','explained-74','explained-75','explained-76','explained-77','explained-78','explained-79','explained-80','explained-81','explained-82','explained-83','explained-84','explained-85','explained-86','explained-87','explained-88','explained-89','explained-90','explained-91','explained-92','explained-93','explained-94','explained-95','explained-96','explained-97','explained-98','explained-99','explained-100'
  ) and image_url is not null and image_uri is not null) <> 80 then
    raise exception 'Explained remaining release incomplete; rolling back';
  end if;
end
$$;

commit;
